/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gapi.Program');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.gapi.TimeGrid');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gapi.Program = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gapi.Program, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gapi.Program.displayName = 'proto.gapi.Program';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gapi.Program.prototype.toObject = function(opt_includeInstance) {
  return proto.gapi.Program.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gapi.Program} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gapi.Program.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    slug: jspb.Message.getFieldWithDefault(msg, 2, ""),
    countProduct: jspb.Message.getFieldWithDefault(msg, 3, 0),
    isLast: jspb.Message.getFieldWithDefault(msg, 4, false),
    timeGrid: (f = msg.getTimeGrid()) && proto.gapi.TimeGrid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gapi.Program}
 */
proto.gapi.Program.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gapi.Program;
  return proto.gapi.Program.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gapi.Program} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gapi.Program}
 */
proto.gapi.Program.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSlug(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCountProduct(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsLast(value);
      break;
    case 5:
      var value = new proto.gapi.TimeGrid;
      reader.readMessage(value,proto.gapi.TimeGrid.deserializeBinaryFromReader);
      msg.setTimeGrid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gapi.Program.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gapi.Program.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gapi.Program} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gapi.Program.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSlug();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCountProduct();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getIsLast();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTimeGrid();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.gapi.TimeGrid.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.gapi.Program.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.gapi.Program.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string slug = 2;
 * @return {string}
 */
proto.gapi.Program.prototype.getSlug = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.gapi.Program.prototype.setSlug = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 count_product = 3;
 * @return {number}
 */
proto.gapi.Program.prototype.getCountProduct = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.gapi.Program.prototype.setCountProduct = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool is_last = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.gapi.Program.prototype.getIsLast = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.gapi.Program.prototype.setIsLast = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional TimeGrid time_grid = 5;
 * @return {?proto.gapi.TimeGrid}
 */
proto.gapi.Program.prototype.getTimeGrid = function() {
  return /** @type{?proto.gapi.TimeGrid} */ (
    jspb.Message.getWrapperField(this, proto.gapi.TimeGrid, 5));
};


/** @param {?proto.gapi.TimeGrid|undefined} value */
proto.gapi.Program.prototype.setTimeGrid = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.gapi.Program.prototype.clearTimeGrid = function() {
  this.setTimeGrid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gapi.Program.prototype.hasTimeGrid = function() {
  return jspb.Message.getField(this, 5) != null;
};


