/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gapi.ResponseGetProgramsByCountry');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.gapi.Country');
goog.require('proto.gapi.Program');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gapi.ResponseGetProgramsByCountry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gapi.ResponseGetProgramsByCountry.repeatedFields_, null);
};
goog.inherits(proto.gapi.ResponseGetProgramsByCountry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gapi.ResponseGetProgramsByCountry.displayName = 'proto.gapi.ResponseGetProgramsByCountry';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gapi.ResponseGetProgramsByCountry.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gapi.ResponseGetProgramsByCountry.prototype.toObject = function(opt_includeInstance) {
  return proto.gapi.ResponseGetProgramsByCountry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gapi.ResponseGetProgramsByCountry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gapi.ResponseGetProgramsByCountry.toObject = function(includeInstance, msg) {
  var f, obj = {
    country: (f = msg.getCountry()) && proto.gapi.Country.toObject(includeInstance, f),
    programsList: jspb.Message.toObjectList(msg.getProgramsList(),
    proto.gapi.Program.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gapi.ResponseGetProgramsByCountry}
 */
proto.gapi.ResponseGetProgramsByCountry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gapi.ResponseGetProgramsByCountry;
  return proto.gapi.ResponseGetProgramsByCountry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gapi.ResponseGetProgramsByCountry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gapi.ResponseGetProgramsByCountry}
 */
proto.gapi.ResponseGetProgramsByCountry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gapi.Country;
      reader.readMessage(value,proto.gapi.Country.deserializeBinaryFromReader);
      msg.setCountry(value);
      break;
    case 2:
      var value = new proto.gapi.Program;
      reader.readMessage(value,proto.gapi.Program.deserializeBinaryFromReader);
      msg.addPrograms(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gapi.ResponseGetProgramsByCountry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gapi.ResponseGetProgramsByCountry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gapi.ResponseGetProgramsByCountry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gapi.ResponseGetProgramsByCountry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCountry();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.gapi.Country.serializeBinaryToWriter
    );
  }
  f = message.getProgramsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.gapi.Program.serializeBinaryToWriter
    );
  }
};


/**
 * optional Country country = 1;
 * @return {?proto.gapi.Country}
 */
proto.gapi.ResponseGetProgramsByCountry.prototype.getCountry = function() {
  return /** @type{?proto.gapi.Country} */ (
    jspb.Message.getWrapperField(this, proto.gapi.Country, 1));
};


/** @param {?proto.gapi.Country|undefined} value */
proto.gapi.ResponseGetProgramsByCountry.prototype.setCountry = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.gapi.ResponseGetProgramsByCountry.prototype.clearCountry = function() {
  this.setCountry(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gapi.ResponseGetProgramsByCountry.prototype.hasCountry = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Program programs = 2;
 * @return {!Array.<!proto.gapi.Program>}
 */
proto.gapi.ResponseGetProgramsByCountry.prototype.getProgramsList = function() {
  return /** @type{!Array.<!proto.gapi.Program>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gapi.Program, 2));
};


/** @param {!Array.<!proto.gapi.Program>} value */
proto.gapi.ResponseGetProgramsByCountry.prototype.setProgramsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.gapi.Program=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gapi.Program}
 */
proto.gapi.ResponseGetProgramsByCountry.prototype.addPrograms = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.gapi.Program, opt_index);
};


proto.gapi.ResponseGetProgramsByCountry.prototype.clearProgramsList = function() {
  this.setProgramsList([]);
};


