/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gapi.ResponseProductList');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.gapi.Product');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gapi.ResponseProductList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gapi.ResponseProductList.repeatedFields_, null);
};
goog.inherits(proto.gapi.ResponseProductList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gapi.ResponseProductList.displayName = 'proto.gapi.ResponseProductList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gapi.ResponseProductList.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gapi.ResponseProductList.prototype.toObject = function(opt_includeInstance) {
  return proto.gapi.ResponseProductList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gapi.ResponseProductList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gapi.ResponseProductList.toObject = function(includeInstance, msg) {
  var f, obj = {
    nextPage: jspb.Message.getFieldWithDefault(msg, 1, 0),
    previousPage: jspb.Message.getFieldWithDefault(msg, 2, 0),
    productsList: jspb.Message.toObjectList(msg.getProductsList(),
    proto.gapi.Product.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gapi.ResponseProductList}
 */
proto.gapi.ResponseProductList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gapi.ResponseProductList;
  return proto.gapi.ResponseProductList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gapi.ResponseProductList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gapi.ResponseProductList}
 */
proto.gapi.ResponseProductList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNextPage(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPreviousPage(value);
      break;
    case 3:
      var value = new proto.gapi.Product;
      reader.readMessage(value,proto.gapi.Product.deserializeBinaryFromReader);
      msg.addProducts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gapi.ResponseProductList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gapi.ResponseProductList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gapi.ResponseProductList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gapi.ResponseProductList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNextPage();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getPreviousPage();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getProductsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.gapi.Product.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 next_page = 1;
 * @return {number}
 */
proto.gapi.ResponseProductList.prototype.getNextPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.gapi.ResponseProductList.prototype.setNextPage = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 previous_page = 2;
 * @return {number}
 */
proto.gapi.ResponseProductList.prototype.getPreviousPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.gapi.ResponseProductList.prototype.setPreviousPage = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated Product products = 3;
 * @return {!Array.<!proto.gapi.Product>}
 */
proto.gapi.ResponseProductList.prototype.getProductsList = function() {
  return /** @type{!Array.<!proto.gapi.Product>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gapi.Product, 3));
};


/** @param {!Array.<!proto.gapi.Product>} value */
proto.gapi.ResponseProductList.prototype.setProductsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.gapi.Product=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gapi.Product}
 */
proto.gapi.ResponseProductList.prototype.addProducts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.gapi.Product, opt_index);
};


proto.gapi.ResponseProductList.prototype.clearProductsList = function() {
  this.setProductsList([]);
};


